version: '3.4'
services:
  truffle:
    build:
      context: .
    image: market-protocol:1.0.1
    command: truffle develop
    tmpfs: 
      - /app/build
      - /app/node_modules:exec,mode=777
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
    stdin_open: true

  truffle-guard:
    image: dadarek/wait-for-dependencies
    depends_on:
      - truffle
    command: truffle:${TRUFFLE_DEVELOP_PORT}

  eth-bridge:
    image: marketproject/ethereum-bridge:0.5.6
    command: -H ${TRUFFLE_DEVELOP_HOST}:${TRUFFLE_DEVELOP_PORT} -a 9 --dev
    restart: unless-stopped
    depends_on:
      - truffle-guard
    links:
      - truffle

  truffle-coverage:
    build:
      context: .
    image: market-protocol:1.0.1
    command: scripts/coverage_setup.sh
    tmpfs: 
      - /app/build
      - /app/node_modules:exec,mode=777
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
    stdin_open: true

  truffle-coverage-guard:
    image: dadarek/wait-for-dependencies
    depends_on:
      - truffle-coverage
    command: truffle-coverage:${TRUFFLE_COVERAGE_PORT}

  eth-bridge-coverage:
    image: marketproject/ethereum-bridge:0.5.6
    command: -H ${TRUFFLE_COVERAGE_HOST}:${TRUFFLE_COVERAGE_PORT} -a 9 --dev
    restart: unless-stopped
    depends_on:
      - truffle-coverage-guard
    links:
      - truffle-coverage
